name: CI

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
        cache-dependency-path: 'web/package-lock.json'
    - name: Install JS dependencies
      run: npm i
    - name: Install PHP dependencies
      run: composer i
    - name: Build scripts
      run: npm run build
    - name: Deploy
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DEPLOY_HOST }}
        username: ${{ secrets.DEPLOY_USER }}
        port: 22
        key: ${{ secrets.DEPLOY_SSHKEY }}
        source: "web/css/,web/img/,web/index.php,web/js/,web/node_modules/,web/package-lock.json,web/package.json,web/php/,web/templates/,web/vendor/"
        target: ${{ secrets.DEPLOY_TARGET }}
        strip_components: 1
