name: CI

on: [ push, pull_request ]

jobs:
  front:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
        cache-dependency-path: 'web/package-lock.json'
    - name: Install JS dependencies
      run: npm i
    - name: Install PHP dependencies
      run: composer i
    - name: Build scripts
      run: npm run build

    - uses: actions/upload-artifact@v4
      with:
        name: front
        path: |
          web/css/
          web/img/
          web/js/
          web/node_modules/
          web/php/
          web/templates/
          web/vendor/
          web/favicon.ico
          web/index.php
        if-no-files-found: error

  api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./api

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish Sanara
      run: dotnet publish -c Release -r linux-x64

    - uses: actions/upload-artifact@v4
      with:
        name: back
        path: api/bin/Release/net8.0/linux-x64/
        if-no-files-found: error