name: CI

on: [ push, pull_request ]

jobs:
  front:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./web

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
        cache-dependency-path: 'web/package-lock.json'
    - name: Install JS dependencies
      run: npm i
    - name: Install PHP dependencies
      run: composer i
    - name: Build scripts
      run: npm run build

    - uses: actions/upload-artifact@v4
      with:
        name: front
        path: |
          web/css/
          web/img/
          web/js/
          web/node_modules/
          web/php/
          web/templates/
          web/vendor/
          web/favicon.ico
          web/index.php
          web/tools.php
          web/translations/
        if-no-files-found: error

  api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Create release
      run: dotnet publish -c Release -r linux-x64

    - uses: actions/upload-artifact@v4
      with:
        name: back
        path: backend/api/bin/Release/net8.0/linux-x64/publish
        if-no-files-found: error

  extension:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./extension

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
        cache-dependency-path: 'web/package-lock.json'
    - name: Install JS dependencies
      run: npm i

    - uses: actions/upload-artifact@v4
      with:
        name: extension
        path: |
          extension/css/
          extension/js/
          extension/node_modules/
          extension/index.html
          extension/options.html
          extension/manifest.json
          extension/_locales/
        if-no-files-found: error

  android:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./android

    steps:
    - uses: actions/checkout@v4
    - name: Set Up JDK
      uses: actions/setup-java@v4
      with:
        distribution: 'zulu' # See 'Supported distributions' for available options
        java-version: '17'
        cache: 'gradle'
    - name: Change wrapper permissions
      run: chmod +x ./gradlew
    - name: Build gradle project
      run: ./gradlew build
    - name: Build apk release project (APK)
      run: ./gradlew assemble

    - uses: actions/upload-artifact@v4
      with:
        name: android
        path: |
          android/app/build/outputs/apk/release/app-release-unsigned.apk
        if-no-files-found: error
